#!/usr/bin/env python3
"""Download authoritative public registries, or regenerate from a saved source directory.
Requires PyYAML: python3 -m pip install PyYAML. The Android app never downloads data.
"""
import argparse
import csv
import hashlib
import json
from pathlib import Path
import subprocess
import yaml

ROOT = Path(__file__).resolve().parent.parent
SOURCES = {
    'company_identifiers.yaml': 'https://bitbucket.org/bluetooth-SIG/public/raw/main/assigned_numbers/company_identifiers/company_identifiers.yaml',
    'oui.csv': 'https://standards-oui.ieee.org/oui/oui.csv',
    'mam.csv': 'https://standards-oui.ieee.org/oui28/mam.csv',
    'oui36.csv': 'https://standards-oui.ieee.org/oui36/oui36.csv',
}
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--sources', type=Path, default=ROOT / 'build/registry-sources')
parser.add_argument('--download', action='store_true')
args = parser.parse_args()
args.sources.mkdir(parents=True, exist_ok=True)
if args.download:
    for filename, url in SOURCES.items():
        # curl's ordinary TLS transport works on IEEE hosts which reject some Python clients.
        subprocess.run(['curl', '--fail', '--location', '--retry', '3', '--max-time', '120', url,
                        '--output', str(args.sources / filename)], check=True)

def clean(value):
    return ' '.join(value.split())

companies = {}
for row in yaml.safe_load((args.sources / 'company_identifiers.yaml').read_text())['company_identifiers']:
    key = f"{row['value']:04X}"
    if key in companies:
        raise ValueError(f'Duplicate company {key}')
    companies[key] = clean(row['name'])
assert len(companies) > 3500, 'Incomplete Bluetooth company source'
ieee = {}
for filename, length in [('oui.csv', 6), ('mam.csv', 7), ('oui36.csv', 9)]:
    rows = list(csv.DictReader((args.sources / filename).open(encoding='utf-8-sig', newline='')))
    assert len(rows) > 1000, f'Incomplete IEEE source {filename}'
    for row in rows:
        key = row['Assignment'].upper()
        assert len(key) == length and all(c in '0123456789ABCDEF' for c in key)
        # IEEE publishes a few historical prefixes with multiple assignees. Keep all names.
        ieee.setdefault(key, set()).add(clean(row['Organization Name']))
ieee = {key: ' / '.join(sorted(names)) for key, names in ieee.items()}
# Generate all outputs only after every input has passed validation.
output = ROOT / 'app/src/main/resources/org/blefinder/core'
output.mkdir(parents=True, exist_ok=True)
for filename, entries in [('companies.tsv', companies), ('ieee.tsv', ieee)]:
    (output / filename).write_text('# Generated by tools/update-offline-registries.py; see docs/OFFLINE_REGISTRIES.md\n' +
        ''.join(f'{key}\t{entries[key]}\n' for key in sorted(entries)), encoding='utf-8')
manifest = {name: {'source': url, 'sha256': hashlib.sha256((args.sources / name).read_bytes()).hexdigest()}
            for name, url in SOURCES.items()}
manifest['counts'] = {'companies': len(companies), 'ieee': len(ieee)}
(output / 'registry-provenance.json').write_text(json.dumps(manifest, indent=2) + '\n')
print(manifest['counts'])
